import { ConnectButton } from '@rainbow-me/rainbowkit';
import { Flex, Text } from '@chakra-ui/react'
import Link from 'next/link'
import Head from 'next/head'

export const Header = () => {
    return (
        <>
            <Head>
                <title>Mini Job DApp</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Flex h="15vh" p="2rem" justifyContent="space-between" alignItems="center">
                <Text>Mini Job DApp</Text>
                <Flex
                    direction={{base : 'column', xl : 'row'}}
                    justifyContent="space-between"
                    alignItems="center"
                    width="25%"
                >
                    <Link href="/">Home</Link>
                    <Link href="/addajob">Add a Job</Link>
                </Flex>
                <ConnectButton />
            </Flex>
        </>
    )
}