import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header/Header'
import useWalletProvider from '@/hooks/useWalletProvider'
import { Text } from '@chakra-ui/react'

export default function Home() {

  const { account } = useWalletProvider()

  return (
    <>
      <Head>
        <title>Advanced Metamask Connexion</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {account ? (  
        <Text>Connected with address {account}</Text>
      ) : (
        <Text>You are not connected</Text>
      )}
    </>
  )
}
