import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react'

export default function Home() {

  const [number, setNumber] = useState(0)

  useEffect(() => {
    console.log("La page vient d'être chargée")
  }, [])

  useEffect(() => {
    console.log("Le state number vient de changer")
  }, [number])

  useEffect(() => {
    console.log("Un rerendering a eu lieu, quelque chose a changé dans l'application")
  })

  return (
    <>
      <Head>
        <title>Increment Decrement APP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <button onClick={() => setNumber(number + 1)}>Increment</button>
        <button onClick={() => setNumber(number - 1)}>Decrement</button>
        {number}
      </div>
      
    </> 
  )
}
